<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "participants"
 *
 * Auto generated by Extension Builder 2020-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Send a message',
    'description' => 'Nachrichten an FE-User und FE-Gruppen senden.
## 1.1.0 :: add a new option for the sender: send the own email adddress to the receiver(s)
## 1.0.1 :: add garbage collection registration',
    'category' => 'plugin',
    'author' => 'C. Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.12-11.5.99',
            'bootstrap_package' => '11.0.2-12.9.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];


